import React from 'react';
import { PredictionResult } from '../types';
import { CheckIcon } from './icons/CheckIcon';
import { AlertIcon } from './icons/AlertIcon';

interface ResultCardProps {
  result: PredictionResult;
}

export const ResultCard: React.FC<ResultCardProps> = ({ result }) => {
  const isLikely = result.outcome.toLowerCase() === 'likely';
  const confidenceColor = isLikely ? 'text-yellow-600' : 'text-green-600';
  const confidenceBg = isLikely ? 'bg-yellow-100' : 'bg-green-100';
  const Icon = isLikely ? AlertIcon : CheckIcon;
  const iconColor = isLikely ? 'text-yellow-500' : 'text-green-500';

  const handleDownloadReport = () => {
    const reportContent = `
Cleftix AI Screening Report
===========================

Prediction Outcome: ${result.outcome}
Confidence Score: ${result.confidence}%
AI Recommendation: ${result.recommendation}

---------------------------

** IMPORTANT DISCLAIMER **
This report was generated by the Cleftix AI screening tool. It is intended for preliminary informational purposes only and is NOT a medical diagnosis. The analysis is based on an algorithmic interpretation of an uploaded image and does not replace the evaluation and expertise of a qualified healthcare professional.

Please consult a doctor or other qualified healthcare provider for a definitive diagnosis, medical advice, and treatment options. Do not disregard professional medical advice or delay in seeking it because of something you have read in this report.
    `;

    const blob = new Blob([reportContent.trim()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'cleftix_report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 animate-fade-in">
        <div className="flex items-center space-x-4 mb-5">
            <div className={`flex-shrink-0 w-10 h-10 flex items-center justify-center ${confidenceBg} rounded-full animate-bounce-in`}>
                <Icon className={`w-6 h-6 ${iconColor}`} />
            </div>
            <div>
                <h3 className={`text-xl font-bold ${confidenceColor}`}>
                    Prediction: {result.outcome}
                </h3>
                <p className="text-gray-600">
                    Confidence Score: {result.confidence}%
                </p>
            </div>
        </div>
        <button 
            onClick={handleDownloadReport}
            className="w-full bg-blue-600 text-white font-bold py-3 px-4 rounded-lg hover:bg-blue-700 transition-all focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
            Download Report
        </button>
    </div>
  );
};
